# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='posts',
            new_name='post',
        ),
    ]
