# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='taged',
        ),
        migrations.AddField(
            model_name='post',
            name='taged',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
