# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160311_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='taged',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag'),
        ),
    ]
