# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161118_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='post',
            new_name='posts',
        ),
    ]
