# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160108_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='emailaccept',
            field=models.BooleanField(default=False),
        ),
    ]
